name: quiz_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  cupertino_icons: ^1.0.2
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/questions.json


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
